# Generated by Django 5.2.4 on 2025-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('email_pdf', models.FileField(upload_to='project_pdfs/email_pdfs/')),
                ('comparison_pdf', models.FileField(upload_to='project_pdfs/comparison_pdfs/')),
                ('approvers', models.ManyToManyField(related_name='projects_approved', to='projectManager.person')),
                ('workers', models.ManyToManyField(related_name='projects_worked_on', to='projectManager.person')),
                ('webpages', models.ManyToManyField(related_name='projects', to='projectManager.webpage')),
            ],
        ),
    ]
