# Generated by Django 5.2.4 on 2025-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comparison_pdf',
        ),
        migrations.RemoveField(
            model_name='project',
            name='email_pdf',
        ),
        migrations.AddField(
            model_name='project',
            name='comparison_pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Comparison PDF URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='email_pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Email PDF URL'),
        ),
    ]
