# Generated by Django 5.2.4 on 2025-07-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0002_remove_project_comparison_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='workers',
            new_name='team_members',
        ),
    ]
