# Generated by Django 5.2.4 on 2025-07-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0005_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
